version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./class_labels:/app/class_labels
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    # Windowsでは以下のネットワーク設定が必要な場合があります
    network_mode: "host" 