version: '3.8'

services:
  app:
    # ローカルビルドの場合
    build: .
    # Docker Hubからのプルを使用する場合はこちらを有効化
    # image: gentoku24/anotation-tool:latest
    # 特定バージョンを使用する場合はこちらを有効化
    # image: gentoku24/anotation-tool:v1.0-20250528
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./class_labels:/app/class_labels
      # OpenGLのアクセスを有効化
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - QT_XCB_GL_INTEGRATION=none
      - LIBGL_ALWAYS_INDIRECT=1
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    # Windowsでは以下のネットワーク設定が必要な場合があります
    network_mode: "host"
    # グラフィックスハードウェアへのアクセスを有効化
    devices:
      - /dev/dri:/dev/dri 